"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.homeElement = void 0;
var lit_1 = require("lit");
var generalSecondarySpan_1 = require("./spans/generalSecondarySpan");
var homeElement = function (main, config, _a) {
    var home = _a.home, entities = _a.entities, templatesObj = _a.templatesObj, homeUsageToDisplay = _a.homeUsageToDisplay, homeSolarCircumference = _a.homeSolarCircumference, circleCircumference = _a.circleCircumference, homeBatteryCircumference = _a.homeBatteryCircumference, homeNonFossilCircumference = _a.homeNonFossilCircumference, homeGridCircumference = _a.homeGridCircumference, individual = _a.individual;
    var showHomeLabel = individual.filter(function (i) { return i.has; }).length <= 1;
    return (0, lit_1.html)(templateObject_7 || (templateObject_7 = __makeTemplateObject(["<div class=\"circle-container home\">\n  <div\n    class=\"circle\"\n    id=\"home-circle\"\n    @click=", "\n    @keyDown=", "\n  >\n    ", "\n    ", "\n    ", "\n    <svg class=\"home-circle-sections\">\n      ", "\n      ", "\n      ", "\n      <circle\n        class=\"grid\"\n        cx=\"40\"\n        cy=\"40\"\n        r=\"38\"\n        stroke-dasharray=\"", " ", "\"\n        stroke-dashoffset=\"0\"\n        shape-rendering=\"geometricPrecision\"\n      />\n    </svg>\n  </div>\n  ", "\n</div>\n</div>"], ["<div class=\"circle-container home\">\n  <div\n    class=\"circle\"\n    id=\"home-circle\"\n    @click=", "\n    @keyDown=", "\n  >\n    ", "\n    ", "\n    ", "\n    <svg class=\"home-circle-sections\">\n      ", "\n      ", "\n      ", "\n      <circle\n        class=\"grid\"\n        cx=\"40\"\n        cy=\"40\"\n        r=\"38\"\n        stroke-dasharray=\"", " ", "\"\n        stroke-dashoffset=\"0\"\n        shape-rendering=\"geometricPrecision\"\n      />\n    </svg>\n  </div>\n  ", "\n</div>\n</div>"])), function (e) {
        var _a, _b;
        main.openDetails(e, (_a = entities.home) === null || _a === void 0 ? void 0 : _a.tap_action, (_b = entities.home) === null || _b === void 0 ? void 0 : _b.entity);
    }, function (e) {
        var _a, _b;
        if (e.key === "Enter") {
            main.openDetails(e, (_a = entities.home) === null || _a === void 0 ? void 0 : _a.tap_action, (_b = entities.home) === null || _b === void 0 ? void 0 : _b.entity);
        }
    }, (0, generalSecondarySpan_1.generalSecondarySpan)(main.hass, main, config, templatesObj, home, "home"), home.icon !== " " ? (0, lit_1.html)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["<ha-icon id=\"home-icon\" .icon=", " />"], ["<ha-icon id=\"home-icon\" .icon=", " />"])), home.icon) : null, homeUsageToDisplay, homeSolarCircumference !== undefined
        ? (0, lit_1.svg)(templateObject_2 || (templateObject_2 = __makeTemplateObject(["<circle\n                class=\"solar\"\n                cx=\"40\"\n                cy=\"40\"\n                r=\"38\"\n                stroke-dasharray=\"", " ", "\"\n                shape-rendering=\"geometricPrecision\"\n                stroke-dashoffset=\"-", "\"\n              />"], ["<circle\n                class=\"solar\"\n                cx=\"40\"\n                cy=\"40\"\n                r=\"38\"\n                stroke-dasharray=\"", " ", "\"\n                shape-rendering=\"geometricPrecision\"\n                stroke-dashoffset=\"-", "\"\n              />"])), homeSolarCircumference, circleCircumference - homeSolarCircumference, circleCircumference - homeSolarCircumference) : "", homeBatteryCircumference
        ? (0, lit_1.svg)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["<circle\n                class=\"battery\"\n                cx=\"40\"\n                cy=\"40\"\n                r=\"38\"\n                stroke-dasharray=\"", " ", "\"\n                stroke-dashoffset=\"-", "\"\n                shape-rendering=\"geometricPrecision\"\n              />"], ["<circle\n                class=\"battery\"\n                cx=\"40\"\n                cy=\"40\"\n                r=\"38\"\n                stroke-dasharray=\"", " ", "\"\n                stroke-dashoffset=\"-", "\"\n                shape-rendering=\"geometricPrecision\"\n              />"])), homeBatteryCircumference, circleCircumference - homeBatteryCircumference, circleCircumference - homeBatteryCircumference - (homeSolarCircumference || 0)) : "", homeNonFossilCircumference !== undefined
        ? (0, lit_1.svg)(templateObject_4 || (templateObject_4 = __makeTemplateObject(["<circle\n                class=\"low-carbon\"\n                cx=\"40\"\n                cy=\"40\"\n                r=\"38\"\n                stroke-dasharray=\"", " ", "\"\n                stroke-dashoffset=\"-", "\"\n                shape-rendering=\"geometricPrecision\"\n              />"], ["<circle\n                class=\"low-carbon\"\n                cx=\"40\"\n                cy=\"40\"\n                r=\"38\"\n                stroke-dasharray=\"", " ", "\"\n                stroke-dashoffset=\"-", "\"\n                shape-rendering=\"geometricPrecision\"\n              />"])), homeNonFossilCircumference, circleCircumference - homeNonFossilCircumference, circleCircumference - homeNonFossilCircumference - (homeBatteryCircumference || 0) - (homeSolarCircumference || 0)) : "", homeGridCircumference !== null && homeGridCircumference !== void 0 ? homeGridCircumference : circleCircumference - homeSolarCircumference - (homeBatteryCircumference || 0), homeGridCircumference !== undefined ? circleCircumference - homeGridCircumference : homeSolarCircumference + (homeBatteryCircumference || 0), !showHomeLabel ? (0, lit_1.html)(templateObject_5 || (templateObject_5 = __makeTemplateObject(["<span class=\"label\"></span>"], ["<span class=\"label\"></span>"]))) : (0, lit_1.html)(templateObject_6 || (templateObject_6 = __makeTemplateObject(["<span class=\"label\">", "</span>"], ["<span class=\"label\">", "</span>"])), home.name));
};
exports.homeElement = homeElement;
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7;
