"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.individualLeftBottomElement = void 0;
var lit_1 = require("lit");
var checkShouldShowDots_1 = require("../utils/checkShouldShowDots");
var computeFlowRate_1 = require("../utils/computeFlowRate");
var showLine_1 = require("../utils/showLine");
var styleLine_1 = require("../utils/styleLine");
var individualSecondarySpan_1 = require("./spans/individualSecondarySpan");
var individualLeftBottomElement = function (main, config, _a) {
    var _b, _c, _d, _e, _f, _g, _h;
    var individualObj = _a.individualObj, templatesObj = _a.templatesObj, displayState = _a.displayState, newDur = _a.newDur;
    if (!individualObj)
        return (0, lit_1.html)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["<div class=\"spacer\"></div>"], ["<div class=\"spacer\"></div>"])));
    var indexOfIndividual = ((_c = (_b = config === null || config === void 0 ? void 0 : config.entities) === null || _b === void 0 ? void 0 : _b.individual) === null || _c === void 0 ? void 0 : _c.findIndex(function (e) { return e.entity === individualObj.entity; })) || 0;
    var duration = newDur.individual[indexOfIndividual] || 0;
    return (0, lit_1.html)(templateObject_8 || (templateObject_8 = __makeTemplateObject(["<div class=\"circle-container individual-bottom bottom\">\n    ", "\n    <div\n      class=\"circle\"\n      @click=", "\n      @keyDown=", "\n    >\n      ", "\n      ", "\n      ", "\n    </div>\n    <span class=\"label\">", "</span>\n  </div> "], ["<div class=\"circle-container individual-bottom bottom\">\n    ", "\n    <div\n      class=\"circle\"\n      @click=", "\n      @keyDown=", "\n    >\n      ", "\n      ", "\n      ", "\n    </div>\n    <span class=\"label\">", "</span>\n  </div> "])), (0, showLine_1.showLine)(config, (individualObj === null || individualObj === void 0 ? void 0 : individualObj.state) || 0) && !((_d = config.entities.home) === null || _d === void 0 ? void 0 : _d.hide)
        ? (0, lit_1.html)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n          <svg width=\"80\" height=\"30\">\n            <path d=\"M40 40 v-40\" id=\"individual-bottom\" class=\"", "\" />\n            ", "\n          </svg>\n        "], ["\n          <svg width=\"80\" height=\"30\">\n            <path d=\"M40 40 v-40\" id=\"individual-bottom\" class=\"", "\" />\n            ", "\n          </svg>\n        "])), (0, styleLine_1.styleLine)((individualObj === null || individualObj === void 0 ? void 0 : individualObj.state) || 0, config), (0, checkShouldShowDots_1.checkShouldShowDots)(config) && (individualObj === null || individualObj === void 0 ? void 0 : individualObj.state) && individualObj.state >= ((_e = individualObj.displayZeroTolerance) !== null && _e !== void 0 ? _e : 0)
            ? (0, lit_1.svg)(templateObject_2 || (templateObject_2 = __makeTemplateObject(["<circle\n                                r=\"1.75\"\n                                class=\"individual-bottom\"\n                                vector-effect=\"non-scaling-stroke\"\n                              >\n                                <animateMotion\n                                  dur=\"", "s\"\n                                  repeatCount=\"indefinite\"\n                                  calcMode=\"linear\"\n                                  keyPoints=", "\n                                  keyTimes=\"0;1\"\n                                >\n                                  <mpath xlink:href=\"#individual-bottom\" />\n                                </animateMotion>\n                              </circle>"], ["<circle\n                                r=\"1.75\"\n                                class=\"individual-bottom\"\n                                vector-effect=\"non-scaling-stroke\"\n                              >\n                                <animateMotion\n                                  dur=\"", "s\"\n                                  repeatCount=\"indefinite\"\n                                  calcMode=\"linear\"\n                                  keyPoints=", "\n                                  keyTimes=\"0;1\"\n                                >\n                                  <mpath xlink:href=\"#individual-bottom\" />\n                                </animateMotion>\n                              </circle>"])), (0, computeFlowRate_1.computeIndividualFlowRate)(((_f = individualObj.field) === null || _f === void 0 ? void 0 : _f.calculate_flow_rate) !== false, duration), individualObj.invertAnimation ? "0;1" : "1;0") : "") : (0, lit_1.html)(templateObject_4 || (templateObject_4 = __makeTemplateObject([" <svg width=\"80\" height=\"30\"></svg> "], [" <svg width=\"80\" height=\"30\"></svg> "]))), function (e) {
        var _a;
        main.openDetails(e, (_a = individualObj === null || individualObj === void 0 ? void 0 : individualObj.field) === null || _a === void 0 ? void 0 : _a.tap_action, individualObj === null || individualObj === void 0 ? void 0 : individualObj.entity);
    }, function (e) {
        var _a;
        if (e.key === "Enter") {
            main.openDetails(e, (_a = individualObj === null || individualObj === void 0 ? void 0 : individualObj.field) === null || _a === void 0 ? void 0 : _a.tap_action, individualObj === null || individualObj === void 0 ? void 0 : individualObj.entity);
        }
    }, (0, individualSecondarySpan_1.individualSecondarySpan)(main.hass, main, config, templatesObj, individualObj, indexOfIndividual, "left-bottom"), (individualObj === null || individualObj === void 0 ? void 0 : individualObj.icon) !== " " ? (0, lit_1.html)(templateObject_5 || (templateObject_5 = __makeTemplateObject([" <ha-icon id=\"individual-left-bottom-icon\" .icon=", " />"], [" <ha-icon id=\"individual-left-bottom-icon\" .icon=", " />"])), individualObj === null || individualObj === void 0 ? void 0 : individualObj.icon) : null, ((_g = individualObj === null || individualObj === void 0 ? void 0 : individualObj.field) === null || _g === void 0 ? void 0 : _g.display_zero_state) !== false || ((individualObj === null || individualObj === void 0 ? void 0 : individualObj.state) || 0) > ((_h = individualObj.displayZeroTolerance) !== null && _h !== void 0 ? _h : 0)
        ? (0, lit_1.html)(templateObject_7 || (templateObject_7 = __makeTemplateObject([" <span class=\"individual-bottom individual-left-bottom\"\n            >", "", "\n          </span>"], [" <span class=\"individual-bottom individual-left-bottom\"\n            >", "", "\n          </span>"])), (individualObj === null || individualObj === void 0 ? void 0 : individualObj.showDirection)
            ? (0, lit_1.html)(templateObject_6 || (templateObject_6 = __makeTemplateObject(["<ha-icon class=\"small\" .icon=", "></ha-icon>"], ["<ha-icon class=\"small\" .icon=", "></ha-icon>"])), (individualObj === null || individualObj === void 0 ? void 0 : individualObj.invertAnimation) ? "mdi:arrow-up" : "mdi:arrow-down") : "", displayState) : "", individualObj === null || individualObj === void 0 ? void 0 : individualObj.name);
};
exports.individualLeftBottomElement = individualLeftBottomElement;
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8;
